### ISSUE TITLE
Health Check which require dependencies via DI 

### ISSUE THREAD

**Issue by afmuller** [AppMetrics/AspNetCoreHealth#10]
Hi

I am new to App Metrics and have a question. I have a project on .net core 2.1.0. 
I have a health check which has external dependencies which need to be loaded by the dependency injector. How do I go about adding this Health Check? See below.

I have been able to register it by using RegisterFromAssembly **but would prefer to be more specific about the health check I want loaded** (I dont want all health checks in all assemblies to be loaded, but only the ones specified).

Thanks
Andrew

```
using App.Metrics.Health;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Aerium.Velocity.Infrastructure.HealthChecks
{
    public class MassTransitHealthCheck : HealthCheck
    {
        private readonly MassTransitReceiveEndpointObserver receiveEndpointObserver;

        public MassTransitHealthCheck(MassTransitReceiveEndpointObserver receiveEndpointObserver) : base("MassTransit Health Check")
        {
            this.receiveEndpointObserver = receiveEndpointObserver ?? throw new ArgumentNullException(nameof(receiveEndpointObserver));
        }

        protected override ValueTask<HealthCheckResult> CheckAsync(CancellationToken cancellationToken = default)
        {
            var faultedEnpoints = receiveEndpointObserver.GetFaultedEndpoints(60);
            if (faultedEnpoints.Count > 0)
            {
                var faultedEnpoints3Minutes = receiveEndpointObserver.GetFaultedEndpoints(180);
                if (faultedEnpoints3Minutes.Count > 0)
                {
                    return new ValueTask<HealthCheckResult>(HealthCheckResult.Unhealthy());
                }
                else
                {
                    return new ValueTask<HealthCheckResult>(HealthCheckResult.Degraded());
                }
            }
            else
            {
                return new ValueTask<HealthCheckResult>(HealthCheckResult.Healthy());
            }
        }
    }
}

```

I have been able to register is as follows:

```
namespace Aerium.Velocity.Instance.Worker
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.RegisterWorkerService(Configuration);

            var metrics = AppMetricsHealth.CreateDefaultBuilder()
               .HealthChecks.RegisterFromAssembly(services)
               .BuildAndAddTo(services);

            services.AddHealth(metrics);
            services.AddHealthEndpoints();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, Microsoft.AspNetCore.Hosting.IHostingEnvironment env)
        {
            app.UseHealthAllEndpoints();
        }
    }
}
```

**Comment by ghost** [comment]
Remove all, and only put :

`app.UseHealthAllEndpoints();`


```

services.AddHealth(builder =>
            {
                builder.HealthChecks.AddCheck(new MyHealthCheckWithParamaters(70, 90));
                builder.HealthChecks.AddCheck<MyHealthCheck>();
            });

```

**Comment by afmuller** [comment]
How do I add a health check (MassTransitHealthCheck in by example in the post above) if the health check has external dependencies which require loading via DI?

**Comment by alhardy** [comment]
@afmuller adding a health check by type will inject dependencies, health checks are singletons

**Comment by afmuller** [comment]
Thank you very much @alhardy . 

I have tried the following:

```
            services.AddHealth(builder =>
            {
                builder.HealthChecks.AddCheck<MassTransitHealthCheck>();
            });

            services.AddHealthEndpoints();
```
but I get this compile error: 
MassTransitHealthCheck must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'THealthCheck' in the generic type or method 'IHealthCheckBuilder.AddCheck<THealthCheck>()'. I would appreciate your assistance, I am not sure what I am missing...

This is the health check - which has the dependencies to be injected in the constructor.

```
    public class MassTransitHealthCheck : HealthCheck
    {
        private readonly MassTransitReceiveEndpointObserver receiveEndpointObserver;

        public MassTransitHealthCheck(MassTransitReceiveEndpointObserver receiveEndpointObserver) : base("MassTransit Health Check")
        {
            this.receiveEndpointObserver = receiveEndpointObserver ?? throw new ArgumentNullException(nameof(receiveEndpointObserver));
        }

        protected override ValueTask<HealthCheckResult> CheckAsync(CancellationToken cancellationToken = default)
        {
            var faultedEnpoints = receiveEndpointObserver.GetFaultedEndpoints(60);
            if (faultedEnpoints.Count > 0)
            {
                var faultedEnpoints3Minutes = receiveEndpointObserver.GetFaultedEndpoints(180);
                if (faultedEnpoints3Minutes.Count > 0)
                {
                    return new ValueTask<HealthCheckResult>(HealthCheckResult.Unhealthy());
                }
                else
                {
                    return new ValueTask<HealthCheckResult>(HealthCheckResult.Degraded());
                }
            }
            else
            {
                return new ValueTask<HealthCheckResult>(HealthCheckResult.Healthy());
            }
        }
    }
```

**Comment by alhardy** [comment]
@afmuller options I can think of for now:

- If you decorate the unwated health checks with an `[Obsolete]` attribute they won't be registered
- Dirty, but you could build the service provider to resolve your dependencies when instantiating your specific health checks

**Comment by sfmskywalker** [comment]
I'm running into the same issue. To work around the two proposed workarounds, I think we'd need access to the internal `HealthChecksAsServices` provided by the `App.Metrics.Health.Extensions.DependencyInjection` package so that we can add types ourselves manually. Right now, that's done for us automatically when calling `RegisterFromAssembly`.

Would you accept a PR that allows for the registration of HealthCheck types into `IHealthCheckTypeProvider`? It would be a bit tricky, since I won't be able to call e.g. `AddHealthChecksAsServices` multiple times because internally it instantiates `StaticHealthCheckTypeProvider` and replaces the `IHealthCheckTypeProvider` singleton registration with that new instance. But I think it should be doable and rather useful.

My use case scenario is that I'm building a set of packages providing health check classes. My consuming apps should be able to choose which health check types to register. But as @afmuller pointed out, we can't just use `.AddCheck<T>`, since it requires a type with a default ctor, so we should register the types with the `StaticHealthCheckTypeProvider`.

Come to think of it, perhaps I should just provide my own implementation of that. Then no need to change `App.Metrics.Health.Extensions.DependencyInjection` at all. 🤔 
I'll give that a go. If it works, I can still submit a PR here so others can benefit from it too, if you think it's useful.

**Comment by sfmskywalker** [comment]
Looks like there's no way to do anything without making some types `public` - right now it's pretty much all `internal`.

**Comment by sfmskywalker** [comment]
After some more investigation, it turns out I don't need to change anything at all. All I need to do to register my own HealthCheck types using DI is the following:

```csharp
services
    .AddSingleton<HealthCheck, CosmosDbHealthCheck>()
    .AddSingleton<HealthCheck, RedisHealthCheck>()
    .AddHealthAndMetrics(health => health.BuildAndAddTo(services))
```

Notice that I'm simply registering the HealthCheck types with the service collection and then invoking BuildAndAddToServices. That's all you need :)

**Comment by alhardy** [comment]
Perfect :)
